# This is a basic workflow to help you get started with Actions

name: Generate Firmwares

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: vial-kb/vial-qmk

      - name: Setup and Build
        continue-on-error: true
        run: |
          export QMK_HOME='~/vial-qmk'
          echo 1
          ls ~
          echo 2
          ls ~/work
          echo 3
          ls ~/work/keyboard_firmware
          echo 4
          ls ~/work/keyboard_firmware/keyboard_firmware
          echo 5
          ls ~/work/keyboard_firmware/keyboard_firmware/keyboards
          #cp -r ~/work/keyboard_firmware/keyboard_firmware/corne/vial-qmk/keyboards $QMK_HOME
          #cd $QMK_HOME
          #python3 -m pip install --user qmk
          #qmk compile -kb crkbd -km vial -e CONVERT_TO=helios
