
# 参考 https://github.com/forester521/qmk-config/blob/main/.github/workflows/ci.yml

name: Generate Firmwares
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-default-repo
        uses: actions/checkout@master

      # - name: Checkout-qmk
      #   uses: actions/checkout@master
      #   with:
      #     repository: vial-kb/vial-qmk
      #     #repository: qmk/qmk_firmware
      #     path: '~/qmk_firmware'

      - name: install qmk
        continue-on-error: true
        run: |
          git clone https://github.com/vial-kb/vial-qmk

          python3 -m pip install --user qmk
          qmk setup -y
          ls ./


      - name: copy file
        continue-on-error: true
        run: |
          cp -r -f ./corne/vial-qmk/keyboards ./vial-qmk

          echo cat ./vial-qmk/keyboards/crkbd/keymaps/vial/keymap.c
          cat ./vial-qmk/keyboards/crkbd/keymaps/vial/keymap.c

      - name: build
        continue-on-error: true
        run: |
          cd ./vial-qmk

          make git-submodule

          make crkbd:vial -e CONVERT_TO=helios

          #echo qmk compile -kb crkbd -km vial -e CONVERT_TO=helios
          #qmk compile -kb crkbd -km vial -e CONVERT_TO=helios

          ls ./.build
