# This is a basic workflow to help you get started with Actions

name: Generate Firmwares

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-default-repo
        uses: actions/checkout@v2

      - name: Checkout-vial-qmk
        uses: actions/checkout@v2
        with:
          repository: vial-kb/vial-qmk
          path: './vial-qmk'

      - name: Setup and Build
        continue-on-error: true
        run: |
          export QMK_HOME='~/vial-qmk'
          echo 1
          ls ./
          echo 2
          ls ./vial-qmk
          echo 3
          ls ./vial-qmk/keyboards/crkbd
          echo 4
          cp -r ./corne/vial-qmk/keyboards/ ~/vial-qmk
          echo 5
          ls ./vial-qmk/keyboards/crkbd
