# This is a basic workflow to help you get started with Actions

name: Generate Firmwares

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-default-repo
        uses: actions/checkout@v2

      - name: Checkout-vial-qmk
        uses: actions/checkout@v2
        with:
          repository: vial-kb/vial-qmk
          path: './vial-qmk'

      - name: install qmk
        continue-on-error: true
        run: |
          python3 -m pip install --user qmk

      - name: Setup and Build
        continue-on-error: true
        run: |
          #echo 1
          #ls ./

          #echo 2
          #ls ./vial-qmk

          echo 3 cp -r -f ./corne/vial-qmk/keyboards/* ./vial-qmk/keyboards
          cp -r -f ./corne/vial-qmk/keyboards/* ./vial-qmk/keyboards

          #echo 4
          #ls ./vial-qmk/keyboards/crkbd/keymaps/vial

          echo cat ./vial-qmk/keyboards/crkbd/keymaps/vial/keymap.c
          cat ./vial-qmk/keyboards/crkbd/keymaps/vial/keymap.c

          echo cd ./vial-qmk
          cd ./vial-qmk
          ls ./

          echo qmk compile -kb crkbd -km vial -e CONVERT_TO=helios
          qmk compile -kb crkbd -km vial -e CONVERT_TO=helios

          ls ./.build
