# This is a basic workflow to help you get started with Actions

name: Generate Firmwares

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-default-repo
        uses: actions/checkout@master

      - name: Checkout-vial-qmk
        uses: actions/checkout@master
        with:
          repository: qmk/qmk_firmware
          path: './qmk_firmware'

      - name: install qmk
        continue-on-error: true
        run: |
          python3 -m pip install --user qmk
          qmk setup -y


      - name: copy file
        continue-on-error: true
        run: |
          cp -r -f ./corne/vial-qmk/keyboards ./qmk_firmware

          echo cat ./qmk_firmware/keyboards/crkbd/keymaps/vial/keymap.c
          cat ./qmk_firmware/keyboards/crkbd/keymaps/vial/keymap.c

          cd ./qmk_firmware

      - name: build
        continue-on-error: true
        run: |
          make git-submodule

          #make crkbd:vial -e CONVERT_TO=helios

          #echo qmk compile -kb crkbd -km vial -e CONVERT_TO=helios
          qmk compile -kb crkbd -km vial -e CONVERT_TO=helios

          ls ./.build
