# This is a basic workflow to help you get started with Actions

name: Generate Firmwares

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: vial-kb/vial-qmk
          path: './vial-qmk'

      - name: Setup and Build
        continue-on-error: true
        run: |
          export QMK_HOME='~/vial-qmk'
          echo 1
          ls ~
          echo 2
          ls ~/work
          echo 3
          ls ~/work/keyboard_firmware
          echo 4
          ls ~/work/keyboard_firmware/keyboard_firmware
          echo 5
          ls ./
          echo 5
          ls ./vial-qmk
